service_name          = "my-service"
environment           = "dev"
aws_region            = "eu-west-1"
cluster_name          = "main-ecs-cluster"
vpc_tag_name          = "main"
hosted_zone_name      = "example.com"
domain_name           = "my-service.dev.example.com"
create_ecr_repository = true # dev owns the shared ECR repository
cpu                   = 256
memory                = 512
desired_count         = 1
